services:
  web:
    image: asciisky-web
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Berlin
    restart: unless-stopped
